### ISSUE TITLE
Package for 0.4.0 not available on conda-forge

### ISSUE THREAD

**Issue by fcollonval** [conda-forge/ipyscales-feedstock#5]
This is a weird one. The merge commit on master to bump to 0.4.0 did not trigger the deployment on conda-forge; see https://anaconda.org/conda-forge/ipyscales/files.

So version 0.4.0 is not available on conda-forge.

**Comment by vidartf** [comment]
Xref https://github.com/conda-forge/ipyscales-feedstock/pull/4

**Comment by fcollonval** [comment]
For some strange reason, the CI was not triggered when the merge of #4 occurs (there is no ✔️ for that commit). So the package for version 0.4.0 was not deployed to conda-forge channels:

![image](https://user-images.githubusercontent.com/8435071/74445134-30cbee00-4e76-11ea-9540-709f86713b3e.png)
